In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.svm import SVC

In [28]:
df = pd.read_csv(r"C:\Users\kartikeshwar singh\Downloads\archive (8)\emails.csv")

In [29]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [30]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [31]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [32]:
df.drop(['Email No.'], axis = 1,inplace = True)

In [33]:
X = df.drop(['Prediction'],axis = 1)
y = df['Prediction']

In [35]:
from sklearn.preprocessing import scale
X = scale(X)
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.3,random_state = 43)

In [36]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 7)
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=7)

In [44]:
y_pred = knn.predict(X_test)
print("Predicted values:\n", y_pred)

Predicted values:
 [0 0 1 ... 0 0 0]


In [45]:
print("Predicted values:", y_pred)

Predicted values: [0 0 1 ... 0 0 0]


In [46]:
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[788 282]
 [ 26 456]]


In [47]:
print("Accuracy Score:\n",metrics.accuracy_score(y_test, y_pred) * 100)

Accuracy Score:
 80.15463917525774


In [48]:
model = SVC(C = 1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Predicted values:\n", y_pred)

Predicted values:
 [0 0 1 ... 0 0 1]


In [49]:
print("Accuray Score of SVM:",metrics.accuracy_score(y_test, y_pred) * 100)

Accuray Score of SVM: 91.6881443298969


In [50]:
print("Confusion Matrix:\n",metrics.confusion_matrix(y_true = y_test, y_pred = y_pred))

Confusion Matrix:
 [[1063    7]
 [ 122  360]]
